In [98]:
import pickle
from sklearn.feature_extraction.text import CountVectorizer, TfidfVectorizer
from sklearn.linear_model import LogisticRegression

In [99]:
kappa = pickle.load(open("doc.p", "rb"))

In [100]:
keys = list(kappa.keys())[1:]

In [102]:
c = CountVectorizer()

In [103]:
X = c.fit_transform(kappa.values())

In [104]:
lr = LogisticRegression()
lr.fit(X, y)

LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
          intercept_scaling=1, max_iter=100, multi_class='ovr', n_jobs=1,
          penalty='l2', random_state=None, solver='liblinear', tol=0.0001,
          verbose=0, warm_start=False)

In [105]:
lr.predict([0 for i in range(1814)])

C:\ProgramData\Anaconda3\lib\site-packages\sklearn\utils\validation.py:395: DeprecationWarning: Passing 1d arrays as data is deprecated in 0.17 and will raise ValueError in 0.19. Reshape your data either using X.reshape(-1, 1) if your data has a single feature or X.reshape(1, -1) if it contains a single sample.
  DeprecationWarning)


array([0])

In [106]:
vec = c.build_analyzer()

In [113]:
newf = c.transform(['мобильный клиент интернет сразу стоит отметить'])

In [114]:
y1 = newf.toarray()
y1.sum()

5

In [115]:
lr.predict(y1)

array([0])

In [116]:
c.get_feature_names()

['абсолютно',
 'аватар',
 'автоматизация',
 'автоматически',
 'автоматический',
 'автор',
 'адекватно',
 'администратор',
 'администраторский',
 'администрирование',
 'адрес',
 'адресат',
 'адресный',
 'аета',
 'аиса',
 'активация',
 'активировать',
 'активно',
 'активность',
 'активный',
 'актуальный',
 'акцент',
 'алгоритм',
 'алексей',
 'альбом',
 'альтернативный',
 'ама',
 'анализ',
 'аналитический',
 'аналог',
 'аналогично',
 'аналогичный',
 'андрей',
 'аргумент',
 'архив',
 'архивация',
 'архивировать',
 'архивный',
 'архитектура',
 'асу',
 'атрибут',
 'аудит',
 'аудитория',
 'база',
 'балл',
 'банк',
 'баранов',
 'безопасность',
 'безопастность',
 'бесплатный',
 'библиотека',
 'бизнес',
 'билдинга',
 'биография',
 'благо',
 'благодаря',
 'ближний',
 'близкий',
 'блог',
 'блок',
 'блокирование',
 'блокироваться',
 'блокировка',
 'бобриковый',
 'бобробанк',
 'бокс',
 'больший',
 'большинство',
 'бпо',
 'браузер',
 'будут',
 'будущее',
 'будущий',
 'букмарклет',
 'быстро',
 'быстры

In [112]:
kappa[keys[16]]

'мобильный клиент позволять оставаться связь люба точка интернет сразу стоить отметить функционал приложение смартфон столь велик полный версия множество полезный опция главное являться уведомление подписать либо документ приложение уведомить изменение личный сообщение отображать практически смс новость активность коллега отображаться твиттер смочь труд найти необходимый заметка документ создать собственный обновить статус создать обсуждение поддерживаться внимание отдельный приложение встроить установить шаг скачать приложение случайно наткнуться приложение приложение старый версия система шаг произвести настройка приложение открыть приложение ввести адрес приложение попросить ввести код активация войти система помощь браузер открыть личный меню установка вкладка название гаджет любой шаг наслаждаться работа '

### Новый подход

In [237]:
Text = ['я пошел на работа', 'я пришел с работа', 'пришел пришел с работа', 'он прочитать интересный книга', 'мне нравиться эта книга']

In [238]:
c = TfidfVectorizer()

In [239]:
sparse = c.fit_transform(Text)

In [240]:
sparse.toarray()

array([[ 0.        ,  0.        ,  0.        ,  0.63907044,  0.        ,
         0.        ,  0.63907044,  0.        ,  0.        ,  0.42799292,
         0.        ],
       [ 0.        ,  0.        ,  0.        ,  0.        ,  0.        ,
         0.        ,  0.        ,  0.76944707,  0.        ,  0.63871058,
         0.        ],
       [ 0.        ,  0.        ,  0.        ,  0.        ,  0.        ,
         0.        ,  0.        ,  0.92360774,  0.        ,  0.38333893,
         0.        ],
       [ 0.52335825,  0.42224214,  0.        ,  0.        ,  0.        ,
         0.52335825,  0.        ,  0.        ,  0.52335825,  0.        ,
         0.        ],
       [ 0.        ,  0.42224214,  0.52335825,  0.        ,  0.52335825,
         0.        ,  0.        ,  0.        ,  0.        ,  0.        ,
         0.52335825]])

In [241]:
st1 = sparse.toarray()[0]
st2 = sparse.toarray()[1]
print(st1, st2)
np.dot(st1, st2)/(np.linalg.norm(st1) * np.linalg.norm(st2))

[ 0.          0.          0.          0.63907044  0.          0.
  0.63907044  0.          0.          0.42799292  0.        ] [ 0.          0.          0.          0.          0.          0.          0.
  0.76944707  0.          0.63871058  0.        ]


0.2733636068409106

In [242]:
st3 = sparse.toarray()[2]
(np.dot(st2, st3))/(np.linalg.norm(st3) * np.linalg.norm(st2))

0.95550990462211782

In [243]:
c.get_feature_names()

['интересный',
 'книга',
 'мне',
 'на',
 'нравиться',
 'он',
 'пошел',
 'пришел',
 'прочитать',
 'работа',
 'эта']

In [244]:
from sklearn.cluster import KMeans

In [245]:
km = KMeans(n_clusters=2)

In [246]:
km.fit(sparse.toarray())

KMeans(algorithm='auto', copy_x=True, init='k-means++', max_iter=300,
    n_clusters=2, n_init=10, n_jobs=1, precompute_distances='auto',
    random_state=None, tol=0.0001, verbose=0)

In [247]:
a = []
for i in sparse.toarray():
    a.append(km.predict(i)[0])

C:\ProgramData\Anaconda3\lib\site-packages\sklearn\utils\validation.py:395: DeprecationWarning: Passing 1d arrays as data is deprecated in 0.17 and will raise ValueError in 0.19. Reshape your data either using X.reshape(-1, 1) if your data has a single feature or X.reshape(1, -1) if it contains a single sample.
  DeprecationWarning)
C:\ProgramData\Anaconda3\lib\site-packages\sklearn\utils\validation.py:395: DeprecationWarning: Passing 1d arrays as data is deprecated in 0.17 and will raise ValueError in 0.19. Reshape your data either using X.reshape(-1, 1) if your data has a single feature or X.reshape(1, -1) if it contains a single sample.
  DeprecationWarning)
C:\ProgramData\Anaconda3\lib\site-packages\sklearn\utils\validation.py:395: DeprecationWarning: Passing 1d arrays as data is deprecated in 0.17 and will raise ValueError in 0.19. Reshape your data either using X.reshape(-1, 1) if your data has a single feature or X.reshape(1, -1) if it contains a single sample.
  DeprecationWarn

In [248]:
new = c.transform(['книга'])

In [249]:
new.toarray()

array([[ 0.,  1.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.]])

In [250]:
a

[1, 1, 1, 0, 0]

In [251]:
model = lr.fit(sparse.toarray(), a)

In [252]:
def Predict(st):
    return c.transform([st]).toarray()

In [253]:
print(Predict('работа'), Predict('книга'))

[[ 0.  0.  0.  0.  0.  0.  0.  0.  0.  1.  0.]] [[ 0.  1.  0.  0.  0.  0.  0.  0.  0.  0.  0.]]


In [255]:
model.predict(Predict('работа'))

array([1])